# This is an example configuration file. You'll need to create a config file named config.yaml in the root directory for the app to work. 

enabled_monitors:
  - discord_monitor

settings:
  discord_monitor:
    token: "TOKEN"
    read_interval: 60
    user_id: "USER_ID"