[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "squinted_eye"
version = "0.1.0"
description = "The OSINT tool for real time information and target monitoring"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "pyyaml>=6.0.2",
]

[project.scripts]
dev = "squinted_eye.main:main"

[tool.uv]
package = true